const foods=[
 {id:'bananas',name:'Bananas',qty:'5 pieces',price:1.5,old:5,date:'5 Sep 2026',dist:'0.6 km',seller:'Iris',icon:'🍌',color:'#fff1a8',desc:'A bit ripe but perfect for smoothies or baking.'},
 {id:'strawberries',name:'Fresh Strawberries',qty:'250 g',price:2.5,old:4.6,date:'1 Sep 2026',dist:'1.2 km',seller:'Emily',icon:'🍓',color:'#ffe3e1',desc:'Fresh berries ready to eat today.'},
 {id:'bread',name:'Wholemeal Bread',qty:'1 loaf',price:1,old:3,date:'2 Sep 2026',dist:'0.8 km',seller:'Jack',icon:'🍞',color:'#f6e6c9',desc:'One unopened loaf.'},
 {id:'yogurt',name:'Greek Yogurt',qty:'500 g',price:2,old:4,date:'3 Sep 2026',dist:'1.5 km',seller:'Mia',icon:'🥛',color:'#e7f2ff',desc:'Sealed and kept refrigerated.'},
 {id:'spinach',name:'Spinach',qty:'150 g',price:1,old:3,date:'4 Sep 2026',dist:'2 km',seller:'Tom',icon:'🥬',color:'#e5f5dd',desc:'Good for salads or cooking.'},
 {id:'chicken',name:'Chicken Breast',qty:'300 g',price:4,old:7.5,date:'3 Sep 2026',dist:'2.1 km',seller:'Sam',icon:'🍗',color:'#f9e1db',desc:'Keep refrigerated and cook thoroughly.'}
];
const S=JSON.parse(localStorage.getItem('foodloop')||'{}');
for(const [k,v] of Object.entries({cart:[],favs:[],reserved:[],listings:[],donations:[],draft:{}}))S[k]??=v;
const app=document.querySelector('#app'),toast=document.querySelector('#toast');
const save=()=>{localStorage.setItem('foodloop',JSON.stringify(S));document.querySelector('#cartCount').textContent=S.cart.length};
const cash=n=>`$${Number(n).toFixed(2)}`;
const say=t=>{toast.textContent=t;toast.className='show';setTimeout(()=>toast.className='',1800)};
const go=h=>location.hash=h;
const nav=n=>document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash===`#${n}`));
function card(f){return `<article class="card"><button class="open" data-open="${f.id}"><div class="art" style="background:${f.color}">${f.icon}</div><h3>${f.name}</h3><small>${f.qty}</small><p><b>${cash(f.price)}</b> <del>${cash(f.old)}</del></p><em>Use by: ${f.date}</em><small>⌖ ${f.dist}</small></button><button class="heart" data-fav="${f.id}">${S.favs.includes(f.id)?'♥':'♡'}</button></article>`}
function home(){nav('home');app.innerHTML=`<section class="hero"><div><h1>Good food<br>shouldn’t go to waste.</h1><p>Buy, sell, share and donate near-expiry food in your community.</p><button class="primary" data-go="#buy">Browse near-expiry food →</button></div><aside>🥦 🍅<br>🥕 🥬</aside></section><section class="features"><button data-go="#buy">🛍️ <b>Buy at lower prices</b><small>Great food, lower cost.</small></button><button data-go="#sell">🏷️ <b>Sell instead of throwing</b><small>Give your food a second life.</small></button><button data-go="#donate">❤️ <b>Donate to those in need</b><small>Support your local community.</small></button></section><section class="section"><div class="title"><h2>Near you now</h2><button data-go="#buy">View all →</button></div><div class="grid">${foods.slice(0,4).map(card).join('')}</div></section>`}
function buy(){nav('buy');app.innerHTML=`<section class="page"><h1>Browse near-expiry food</h1><p>Find good food nearby and save it from waste.</p></section><section class="market"><aside class="filters"><h3>Filters</h3><label>Within<select><option>5 km</option><option>2 km</option><option>10 km</option></select></label><label>Maximum price<input id="range" type="range" min="1" max="8" value="8"><b id="rangeText">$8.00</b></label></aside><div><div class="search"><input id="search" placeholder="Search food…"><select id="sort"><option value="near">Sort by: Nearest</option><option value="price">Price: Low to high</option></select></div><div class="grid" id="results"></div></div></section>`;results()}
function results(){let a=[...foods],q=(document.querySelector('#search')?.value||'').toLowerCase(),m=+(document.querySelector('#range')?.value||99);a=a.filter(x=>x.name.toLowerCase().includes(q)&&x.price<=m);if(document.querySelector('#sort')?.value==='price')a.sort((x,y)=>x.price-y);document.querySelector('#results').innerHTML=a.map(card).join('')||'<p>No matching food found.</p>'}
function detail(id){nav('buy');let f=foods.find(x=>x.id===id)||foods[0],r=S.reserved.includes(id);app.innerHTML=`<button class="back" data-go="#buy">← Back to results</button><section class="detail"><div><div class="bigart" style="background:${f.color}">${f.icon}</div><div class="thumbs">${f.icon} ${f.icon} ${f.icon}</div></div><div><h1>${f.name}</h1><p>${f.qty}</p><h2>${cash(f.price)} <del>${cash(f.old)}</del></h2><p>🟠 Use by: ${f.date}<br>Condition: Good (slightly ripe)<br>Storage: Room temperature<br>Location: ${f.dist} (Brisbane)</p><div class="seller"><b>${f.seller}</b><small>Usually replies within 1 hour</small><button data-message="${f.seller}">Message</button></div><div class="actions"><button class="primary" data-add="${id}">Add to cart</button><button class="secondary" data-reserve="${id}">${r?'Reserved ✓':'Buy / Reserve'}</button><button data-fav="${id}">${S.favs.includes(id)?'♥':'♡'}</button></div><h3>About this item</h3><p>${f.desc}</p></div><aside><h3>⌖ Pickup location</h3><p>St Lucia, Brisbane</p><div class="map">📍<small>Map preview</small></div><h4>Safety tips</h4><p>✓ Check food condition<br>✓ Meet in a public place<br>✓ Bring your own bag</p></aside></section>`}
function sell(step=1){nav('sell');app.innerHTML=`<section class="formpage"><div class="page"><h1>List your item</h1><p>It only takes a minute. Help reduce waste and earn a little back.</p></div><div class="steps">${['Item details','Photos','Set price','Review'].map((x,i)=>`<span class="${step>i?'on':''}"><b>${i+1}</b>${x}</span>`).join('')}</div><section class="panel" id="panel"></section></section>`;let p=document.querySelector('#panel'),d=S.draft;if(step===1)p.innerHTML=`<h2>Item details</h2><div class="formgrid"><label>Food name *<input id="foodname" value="${d.name||''}"></label><label>Category *<select id="cat"><option>Fruit & vegetables</option><option>Dairy & eggs</option><option>Bakery</option></select></label><label>Quantity *<input id="qty" type="number" min="1" value="${d.qty||''}"></label><label>Units *<select id="unit"><option>pieces</option><option>g</option><option>kg</option></select></label><label>Expiry date *<input id="expiry" type="date" value="${d.expiry||''}"></label><label>Condition *<select id="condition"><option>Good (slightly ripe)</option><option>Sealed</option></select></label></div><p class="error" id="error"></p><div class="end"><button class="primary" data-snext="2">Next: Photos →</button></div>`;if(step===2)p.innerHTML=`<h2>Add photos</h2><div class="upload">🍌<h3>Upload photos</h3><p>Sample images are used in this prototype.</p><button id="upload">Choose photos</button><p id="uploaded"></p></div><div class="end"><button data-sback="1">Back</button><button class="primary" data-snext="3">Next: Set price →</button></div>`;if(step===3)p.innerHTML=`<h2>Set your price</h2><div class="pricebox"><span>🍌</span><div><h3>${d.name||'Bananas'}</h3><p>Suggested range: $1.00–$2.50</p><label>Your price *<input id="price" type="number" step=".5" value="${d.price||1.5}"></label></div><aside><b>Impact you can make</b><p>♻ Save food from landfill</p><p>❤️ Help someone get affordable food</p></aside></div><div class="end"><button data-sback="2">Back</button><button class="primary" data-snext="4">Next: Review →</button></div>`;if(step===4)p.innerHTML=`<h2>Review your listing</h2><div class="review"><span>🍌</span><div><h2>${d.name||'Bananas'}</h2><p>${d.qty||5} ${d.unit||'pieces'} · ${d.expiry||'5 Sep 2026'}</p><h2>${cash(d.price||1.5)}</h2></div></div><div class="end"><button data-sback="3">Back</button><button class="primary" id="publish">Publish listing</button></div>`}
function listed(){app.innerHTML=`<section class="success"><i>🎉</i><h1>Your item is live!</h1><p>People nearby can now see and reserve your item.</p><button class="primary" data-go="#items">View my listings</button> <button data-go="#sell">Add another item</button></section>`}
function donate(step=1){nav('donate');app.innerHTML=`<section class="donate"><small>FOOD DONATION · DROP-OFF ONLY</small><h1>Share good food<br>with people nearby.</h1><p>Bring your surplus food to a selected community drop-off point.<br><b>Home collection is not currently available.</b></p></section><div class="steps three">${['Choose your food','Confirm the location','Drop it off'].map((x,i)=>`<span class="${step>i?'on':''}"><b>${i+1}</b>${x}</span>`).join('')}</div><section class="panel" id="dpanel"></section>`;let p=document.querySelector('#dpanel');if(step===1)p.innerHTML=`<h2>Choose an eligible item</h2><div class="choices">${foods.slice(0,4).map(f=>`<label><input type="radio" name="donate" value="${f.id}" ${S.donateDraft===f.id?'checked':''}><span>${f.icon}</span><b>${f.name}</b><small>${f.qty}</small></label>`).join('')}</div><div class="end"><button class="primary" data-dnext="2">Continue →</button></div>`;if(step===2)p.innerHTML=`<h2>Confirm your drop-off point</h2><div class="partner"><div class="map">📍<small>West End Community Hub</small></div><div><h3>West End Community Hub</h3><p>17 Boundary Street, West End</p><p><b>Opening hours:</b> Mon–Sat, 9 AM–5 PM</p><p><b>You deliver the food.</b> Home pickup is not available.</p></div></div><div class="end"><button data-dback="1">Back</button><button class="primary" data-dnext="3">Confirm drop-off →</button></div>`;if(step===3)p.innerHTML=`<div class="success compact"><i>💚</i><h1>Donation drop-off confirmed</h1><p>Take the item to <b>West End Community Hub</b> during opening hours.</p><button class="primary" id="doneDonate">Done</button></div>`}
function messages(person='Tom'){nav('');app.innerHTML=`<section class="messages"><aside><h2>Messages</h2>${['Tom','Emily','Jack','Community Hub'].map(n=>`<button data-thread="${n}" class="${n===person?'chosen':''}"><b>${n}</b><small>${n==='Community Hub'?'Thanks for the donation!':'Interested in your listing'}</small></button>`).join('')}</aside><div class="conversation"><h3>${person} <small>Active now</small></h3><div class="chat"><p>Hi! Is this item still available?</p><p class="mine">Yes! It is still available. You can pick it up today.</p><p>Great! Can I come around 5pm?</p><p class="mine">Sure! See you then 😊</p></div><form id="send"><input id="message" placeholder="Type a message…" required><button class="primary">Send</button></form></div></section>`}
function cart(){nav('');let a=S.cart.map(id=>foods.find(f=>f.id===id)).filter(Boolean);app.innerHTML=`<section class="page"><h1>Your cart</h1></section><section class="panel">${a.length?a.map(f=>`<div class="row"><span>${f.icon}</span><b>${f.name}</b><strong>${cash(f.price)}</strong><button data-remove="${f.id}">Remove</button></div>`).join('')+`<div class="total"><b>Total</b><h2>${cash(a.reduce((n,f)=>n+f.price,0))}</h2></div><button class="primary" id="checkout">Continue to simulated checkout</button>`:`<div class="success compact"><h2>Your cart is empty</h2><button data-go="#buy">Browse food</button></div>`}</section>`}
function items(){nav('');app.innerHTML=`<section class="page title"><h1>My items</h1><button class="primary" data-go="#sell">+ Add new item</button></section><section class="panel"><h3>Active (${S.listings.length})</h3>${S.listings.length?S.listings.map((x,i)=>`<div class="row"><span>🍌</span><b>${x.name}</b><strong>${cash(x.price)}</strong><button data-delete="${i}">Delete</button></div>`).join(''):'<div class="success compact"><h2>No listings yet</h2></div>'}</section>`}
function route(){let [r,p]=(location.hash.slice(1)||'home').split('/');({home,buy,sell,donate,cart,items}[r]||(()=>r==='product'?detail(p):r==='messages'?messages(p):home()))()}
document.addEventListener('click',e=>{let x=e.target.closest('[data-go]');if(x)return go(x.dataset.go);x=e.target.closest('[data-open]');if(x)return go('#product/'+x.dataset.open);x=e.target.closest('[data-fav]');if(x){let id=x.dataset.fav;S.favs=S.favs.includes(id)?S.favs.filter(v=>v!==id):[...S.favs,id];save();return route()}x=e.target.closest('[data-add]');if(x){if(!S.cart.includes(x.dataset.add))S.cart.push(x.dataset.add);save();return say('Added to cart')}x=e.target.closest('[data-reserve]');if(x){if(!S.reserved.includes(x.dataset.reserve))S.reserved.push(x.dataset.reserve);save();detail(x.dataset.reserve);return say('Item reserved')}x=e.target.closest('[data-message]');if(x)return go('#messages/'+x.dataset.message);x=e.target.closest('[data-snext]');if(x){let n=+x.dataset.snext;if(n===2){let name=document.querySelector('#foodname').value.trim(),qty=document.querySelector('#qty').value,expiry=document.querySelector('#expiry').value;if(!name||!qty||!expiry){document.querySelector('#error').textContent='Please complete all required fields.';return}S.draft={name,qty,expiry,unit:document.querySelector('#unit').value};save()}if(n===4){S.draft.price=document.querySelector('#price').value;save()}return sell(n)}x=e.target.closest('[data-sback]');if(x)return sell(+x.dataset.sback);if(e.target.id==='upload'){document.querySelector('#uploaded').textContent='✓ 3 sample photos added'}if(e.target.id==='publish'){S.listings.push({...S.draft});save();listed();say('Listing published')}x=e.target.closest('[data-dnext]');if(x){let c=document.querySelector('[name=donate]:checked');if(c)S.donateDraft=c.value;save();return donate(+x.dataset.dnext)}x=e.target.closest('[data-dback]');if(x)return donate(+x.dataset.dback);if(e.target.id==='doneDonate'){S.donations.push(S.donateDraft);save();go('#home');say('Donation recorded')}x=e.target.closest('[data-thread]');if(x)return messages(x.dataset.thread);x=e.target.closest('[data-remove]');if(x){S.cart=S.cart.filter(v=>v!==x.dataset.remove);save();return cart()}x=e.target.closest('[data-delete]');if(x){S.listings.splice(+x.dataset.delete,1);save();return items()}if(e.target.id==='checkout')say('Simulated checkout complete')});
document.addEventListener('input',e=>{if(e.target.matches('#search,#range')){if(e.target.id==='range')document.querySelector('#rangeText').textContent=cash(e.target.value);results()}});document.addEventListener('change',e=>{if(e.target.id==='sort')results()});document.addEventListener('submit',e=>{if(e.target.id==='send'){e.preventDefault();let t=document.querySelector('#message').value,p=document.createElement('p');p.className='mine';p.textContent=t;document.querySelector('.chat').appendChild(p);e.target.reset();say('Message sent')}});document.querySelector('#msg').onclick=()=>go('#messages');document.querySelector('#cart').onclick=()=>go('#cart');document.querySelector('#profile').onclick=()=>go('#items');window.addEventListener('hashchange',route);save();route();
